PROC SQL;
CREATE TABLE WORK.query AS
SELECT STU_ID , X1PAR1EDU , X1PAR2EDU , X1FAMINCOME , X1REGION , X4RFDGMJSTEM , S2ANYAP , S4MAJMAINRSN FROM WORK.IMPORT;
RUN;
QUIT;

PROC DATASETS NOLIST NODETAILS;
CONTENTS DATA=WORK.query OUT=WORK.details;
RUN;

PROC PRINT DATA=WORK.details;
RUN;